### ISSUE TITLE
WSL Troubleshooting: ./deploy.sh: line 2: $'\r': command not found

### ISSUE THREAD

**Issue by Joshua-Donovan** [Azure-Samples/azure-ai-studio-secure-bicep#10]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> clone repository to windows machine
> attempt to execute bash scripts via wsl

### Any log messages given by the failure
> ./deploy.sh: line 2: $'\r': command not found

### Expected/desired behavior
> file runs without error

### OS and Version?
> Windows 11 
> WSL Ubuntu 22.04.3

### Versions
>

### Mention any other details that might be useful
> I am not sure if this is an issue with the repository files directly or the use of WSL for execution. 

> If this is an issue with WSL and not a fix needed in the files, then it might be good to add a troubleshooting section / note to the Readme for this sample.

### Problem: 
- When Bash attempts to execute the script, it reads windows line endings '\r' (rendered as ^M in VIM).

### Solution: 
- Open both deploy.sh and functions.sh in VIM inside WSL. `vim -b deploy.sh` & `vim -b functions.sh`. 

- Remove the windows line endings 
>using file conversion in VIM to set the file to unix did not seem to work with these files example: `:set fileformat:unix` or `:w ++ff:unix`

- use VIM replace `:%s/^M//g` where the ^M is created by `ctrl + v` then `ctrl + m`. 
- After removing the ^M DOS file endings, save with `:wq`

> Thanks! We'll be in touch soon.

**Comment by paolosalvatori** [comment]
Hi @Joshua-Donovan can you please check the selected end of line of the files? You can open the script in Visual Studio and see it in the status bar.

**Comment by Joshua-Donovan** [comment]
Hey @paolosalvatori that must have been it, I cloned directly in ubuntu as a test and the line endings are not an issue with a fresh clone. 

I was editing the files in VSCode before executing in WSL and my VSCode was set to CRLF, so the problem was all me. 

Closing this issue. 

Thanks!
